# This is a basic workflow to help you get started with Actions

name: Slack Notificationのテスト

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Try to fail
        run: exit 0
        
      - name: Echo github.action_path
        run: |
          echo github.action_path: ${{ github.action_path }}
          echo github.event_path: ${{ github.event_path }}
          echo ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
          echo $name

      - name: Slack webhook
        if: failure()
        run: |
          URL=$(gh pr view ${{matrix.branch}} --json url | jq -r ' .url')
          BODY=$(gh pr view ${{matrix.branch}} --json body | jq -r ' .body')

          jq -n '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "This PR is now ready to merge.\nPlease make this PR ready for review.\n'"${URL}"'"
                }
              },
              {
                "type": "section",
                "text": 
                  {
                    "type": "mrkdwn",
                    "text": "*Branch:*\n'"${{matrix.branch}}"'"
                  }
              },
              {
                "type": "section",
                "text": 
                  {
                    "type": "mrkdwn",
                    "text": "*description:*\n'"${BODY}"'"
                  }
              }
            ]
          }' | curl -H 'Content-Type: application/json' -d @- ${{ secrets.XXXX }}
